@echo off
echo Starting AirLink Backend Server...
echo Checking for existing processes on port 3000...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :3000') do taskkill /PID %%a /F >nul 2>&1
echo Starting server...
cd /d "d:\AIRLINKV2\backend"
npm start
pause